#!/usr/bin/env node
/* eslint-disable no-console */
const fs = require("fs");
const path = require("path");

const VSCODE_ROOT = path.join(__dirname, "..");
const ASSETS_DIR = path.join(VSCODE_ROOT, "assets");
const OUT_FILE = path.join(VSCODE_ROOT, "src", "runtime_assets.generated.ts");

const FALLBACK_CONFIG = {};
const FALLBACK_MCP = {};
const FALLBACK_PROMPT = "You are Agent CLi for VS Code.";
const FALLBACK_SECRETS = {};

function readAssetText(fileName, fallback) {
  const p = path.join(ASSETS_DIR, fileName);
  try {
    if (fs.existsSync(p)) return fs.readFileSync(p, "utf8");
  } catch {
    // ignore
  }
  return typeof fallback === "string" ? fallback : JSON.stringify(fallback, null, 2) + "\n";
}

function toB64(value) {
  return Buffer.from(value, "utf8").toString("base64");
}

function generate() {
  const configText = readAssetText("agent.config.json", FALLBACK_CONFIG);
  const mcpText = readAssetText("mcp_catalog.json", FALLBACK_MCP);
  const promptText = readAssetText("agent.prompt.txt", FALLBACK_PROMPT);
  const secretsText = readAssetText(".secrets.json", FALLBACK_SECRETS);

  const out = [
    "/* AUTO-GENERATED FILE. DO NOT EDIT. */",
    "/* Generated by scripts/generate_runtime_assets.cjs */",
    "",
    `export const GENERATED_DEFAULT_CONFIG_B64 = ${JSON.stringify(toB64(configText))};`,
    `export const GENERATED_MCP_CATALOG_B64 = ${JSON.stringify(toB64(mcpText))};`,
    `export const GENERATED_DEFAULT_PROMPT_B64 = ${JSON.stringify(toB64(promptText))};`,
    `export const GENERATED_SECRETS_B64 = ${JSON.stringify(toB64(secretsText))};`,
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, out, "utf8");
  console.log(`Generated ${path.relative(VSCODE_ROOT, OUT_FILE)} from VSCODE/assets`);
}

generate();
